import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pl'>
			<body
				className={`${inter.className}  bg-gradient-to-r from-cyan-950 via-sky-900 to-sky-950 text-white`}
			>
				<Header />
				<main className='-z-1'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
